version: '3'

services:
    db:
        image: postgres:14
        volumes:
            - /private/var/lib/postgresql:/var/lib/postgresql
        ports:
            - "5438:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: teinformatech
        networks: 
            - app-network
    db-elixir:
        image: postgres:14
        volumes:
            - /private/var/lib/postgresql:/var/lib/postgresql
        ports:
            - "5439:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: teinformatech
        networks:
            - app-network
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        entrypoint: dockerize -wait tcp://db:5432 -wait tcp://redis:6379 -timeout 20s docker-entrypoint.sh
        command: npm run start
        networks: 
            - app-network
        ports:
            - "3000:3000"
        volumes: 
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        depends_on: 
            - db

    frontend-site:
        build:
            context: ./frontend/website
            dockerfile: Dockerfile
        container_name: frontend-site
        command: npm run dev -- -p 80
        networks: 
            - app-network
        ports:
            - "80:80"
        volumes: 
            - ./frontend/website:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        depends_on: 
            - backend

    frontend-admin:
        build:
            context: ./frontend/admin
            dockerfile: Dockerfile
        container_name: frontend-admin
        command: npm run start
        networks: 
            - app-network
        ports:
            - "8080:8080"
        volumes: 
            - ./frontend/admin:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        depends_on: 
            - frontend-site
    
    redis:
        image: "redis:alpine"
        networks: 
            - app-network
        ports:
            - "6379:6379"
    # phoenix:
    #   build:
    #      # Here we define that it should build from the current directory.
    #      context: ./elixir
    #      dockerfile: Dockerfile
    #   networks:
    #     - app-network
    #   volumes:
    #     - ./elixir:/app
    #   environment:
    #      DATABASE_URL: ecto://postgres:changeme@postgres/development
    #      SECRET_KEY_BASE: "y+HzGpFdY4OXJq9Ro/QWYbwQnkKaQAy/Mk5/FKN0i5naNfkxSkKmDuQ6vIjOm65r"
    #      # Variables to connect to our Postgres server.
    #      PGUSER: postgres
    #      PGPASSWORD: admin
    #      PGDATABASE: teinformatech
    #      PGPORT: 5439
    #      # Hostname of our Postgres container.
    #      PGHOST: db-elixir
    #   ports:
    #      # Mapping the port to make the Phoenix app accessible outside of the container.
    #      - '4444:4000'
    #   depends_on:
    #      # The postgres container needs to be started before we start this container.
    #      - db-elixir

networks: 
  app-network:
    driver: bridge
